<a href="https://colab.research.google.com/github/JuanCervigon/master2025/blob/main/1_Vectores_y_valores_propios_con_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vectores y valores propios con `numpy`

En este cuaderno se calculan los valores y vectores propios de una matriz $A$


Tomamos la matriz $A$ simétrica y definida positiva para asegurar que los valores y vectores propios son números reales

Se podría hacer el mismo análisis con cualquier matriz cuadrada, pero si la matriz no es definida positiva, los valores y vectores propios podrían ser números complejos

Recordamos las siguientes definiciones


* Una matriz $A$ es simétrica si $A'=A$
* Una matriz $A$ es semi-definida positiva si $x'Ax\ge 0   \hspace{0.5cm}\forall x\neq 0$

Recordamos que todas las matrices de varianzas y covarianzas son simétricas y semi-definidas positivas

El objetivo es familiarizarse con el álgebra de las matrices



In [ ]:
import numpy as np

In [ ]:
# Definir la matriz A, simétrica y definida positiva
A = np.array([[1,.9,.2],[.9,1,.3],[.2,.3,1]])
A

array([[1. , 0.9, 0.2],
       [0.9, 1. , 0.3],
       [0.2, 0.3, 1. ]])

In [ ]:
# Calcular el vector de valores propios y la matriz de vectores propios unitarios

valores_propios, vectores_propios =np.linalg.eig(A)


In [ ]:
# Imprimir la matriz de vectores propios y el vector de valores propios

print('Valores propios\n',valores_propios,'\n\n',
      'Vectores propios\n',vectores_propios)

Valores propios
 [2.02255456 0.09402458 0.88342086] 

 Vectores propios
 [[-0.65954066 -0.69284486 -0.29149978]
 [-0.67657498  0.71615461 -0.17137347]
 [-0.32749414 -0.08419369  0.94109458]]


# ordenar los vectores

In [ ]:
# Ordenar los valores propios de mayor a menor y los vectores propios asociados
orden_valores_propios = np.argsort(valores_propios)[::-1]
valores_propios_ordenados = valores_propios[orden_valores_propios]
vectores_propios_ordenados = vectores_propios[:, orden_valores_propios]

# Imprimir la matriz de vectores propios y el vector de valores propios ordenados
print('Valores propios ordenados\n', valores_propios_ordenados, '\n\n',
      'Vectores propios ordenados\n', vectores_propios_ordenados)

Valores propios ordenados
 [2.02255456 0.88342086 0.09402458] 

 Vectores propios ordenados
 [[-0.65954066 -0.29149978 -0.69284486]
 [-0.67657498 -0.17137347  0.71615461]
 [-0.32749414  0.94109458 -0.08419369]]


# Comprobar las propiedades de los valores y vectores propios

A partir de la matriz $A$ calculamos las matrices $V$ de valores propios y la matriz $L$ con los valores propios en la diagonal y el resto ceros

Comprobamos que se cumplen las siguientes igualdades

* A·V=V·L
* V'·V=I
* V·V'=I


In [ ]:
# Renombrar la matriz V con los vectores propios
V = vectores_propios_ordenados
# Crear la matriz diagonal con los valores propios
L = np.diag(valores_propios_ordenados)


In [ ]:
L

array([[2.02255456, 0.        , 0.        ],
       [0.        , 0.88342086, 0.        ],
       [0.        , 0.        , 0.09402458]])

In [ ]:
# Comprobar la descomposición de la matriz A
# Calcular AV y VL y comprobar que coinciden
print('AV\n',A@V,'\n\n','VL\n',V@L)

AV
 [[-1.33395697 -0.25751699 -0.06514444]
 [-1.36840982 -0.1513949   0.06733613]
 [-0.66237477  0.83138258 -0.00791628]] 

 VL
 [[-1.33395697 -0.25751699 -0.06514444]
 [-1.36840982 -0.1513949   0.06733613]
 [-0.66237477  0.83138258 -0.00791628]]


In [ ]:
# Comprobar V'V=I
V.T@V

array([[ 1.00000000e+00, -1.21035585e-16, -1.42595454e-16],
       [-1.21035585e-16,  1.00000000e+00, -1.62545121e-16],
       [-1.42595454e-16, -1.62545121e-16,  1.00000000e+00]])

In [ ]:
# Comprobar VV'=I
V@V.T

array([[ 1.00000000e+00, -1.75421137e-16,  2.53916583e-17],
       [-1.75421137e-16,  1.00000000e+00, -1.05297944e-16],
       [ 2.53916583e-17, -1.05297944e-16,  1.00000000e+00]])

In [ ]:
# Calcular V'V y mostrar el resultado con cuatro decimales
np.round(V.T@V,4)

array([[ 1., -0., -0.],
       [-0.,  1., -0.],
       [-0., -0.,  1.]])

In [ ]:
# Comprobar VV'=I
np.isclose(V@V.T, np.diag(np.ones(3)))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])